# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-18.04'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '4096'
  end

  config.vm.network "public_network", ip: "192.168.0.55"
  config.vm.synced_folder '.', '/vagrant', owner: 'vagrant', group: 'root'

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      python3-pip \
      software-properties-common
    pip3 install virtualenv
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update
    apt-get install -y docker-ce
    usermod --groups docker --append vagrant
    echo vm.max_map_count=262144 > /etc/sysctl.d/vm_max_map_count.conf
    sysctl --system
    grep -qF 'vagrant - nofile 65536' /etc/security/limits.conf || echo 'vagrant - nofile 65536' >> /etc/security/limits.conf
    curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

    git clone https://github.com/alcateiadev/devops-rancher-gke.git
    cd devops-rancher-gke
    cd c
    docker-compose up -d
    cd ..
    cd sonar
    docker-compose up -d
    cd ..
    docker-compose -f docker-kafka.yml up -d
    docker-compose -f docker-postgres.yml up -d
    docker-compose -f nginx.yml up -d


  SHELL

end