name: Projeto Gnus - Rancher
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Maven project
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build and test project
      run: mvn -f pom.xml clean verify





    # - name: Upload Maven build artifact
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: artifact
    #     path: github-actions-java-maven/target/github-actions-java-maven.jar




#   deploy: 
#     runs-on: ubuntu-latest  
#     needs: build 
#     name: Build Docker container and deploy to Kubernetes
#     steps:
#     - uses: actions/checkout@v1
#     - name: Download Maven build artifact
#       uses: actions/download-artifact@v1
#       with:
#         name: artifact
#     - name: Build Docker container
#       run: |
#         mkdir -p github-actions-java-maven/target
#         mv artifact/github-actions-java-maven.jar github-actions-java-maven/target
#         docker build -t de.rieckpil.blog/github-actions-sample github-actions-java-maven
#     - name: Access secrets
#       env: 
#         SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
#       run: echo "Content of secret - $SUPER_SECRET"
#     - name: Push Docker images
#       run: echo "Pushing Docker image to Container Registry (e.g. ECR)"
#     - name: Deploy application
#       run: echo "Deploying application (e.g. Kubernetes)"
